# Generated by Django 3.2.12 on 2022-02-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
