# Generated by Django 2.2 on 2022-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('start', models.TimeField(auto_now=True)),
                ('end', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
