# Generated by Django 2.2 on 2022-02-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.CharField(default='', max_length=255),
        ),
    ]
