# Generated by Django 2.2 on 2022-02-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='end',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='start',
            new_name='startTime',
        ),
    ]
