# Generated by Django 3.2.11 on 2022-02-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_game_id'),
        ('events', '0002_game_creator'),
    ]

    operations = [
    ]
