# Generated by Django 3.2.11 on 2022-02-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_merge_0002_alter_game_id_0002_game_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creator',
        ),
    ]
