# Generated by Django 2.2 on 2022-02-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220205_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
